// Copyright © SurrealDB Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Deterministic PRNG workload generator for simulation testing.

use bytes::Bytes;
use rand::rngs::StdRng;
use rand::{RngExt, SeedableRng};

use super::model::ModelIsolation;

/// Actions generated by the deterministic workload generator.
#[derive(Debug, Clone)]
pub enum SimAction {
	Begin {
		txn_id: usize,
		write: bool,
		mode: ModelIsolation,
	},
	Get {
		txn_id: usize,
		key: Bytes,
	},
	GetForUpdate {
		txn_id: usize,
		key: Bytes,
	},
	Exists {
		txn_id: usize,
		key: Bytes,
	},
	Set {
		txn_id: usize,
		key: Bytes,
		val: Bytes,
	},
	Put {
		txn_id: usize,
		key: Bytes,
		val: Bytes,
	},
	PutC {
		txn_id: usize,
		key: Bytes,
		val: Bytes,
		chk: Option<Bytes>,
	},
	Del {
		txn_id: usize,
		key: Bytes,
	},
	DelC {
		txn_id: usize,
		key: Bytes,
		chk: Option<Bytes>,
	},
	SetSavepoint {
		txn_id: usize,
	},
	RollbackSavepoint {
		txn_id: usize,
	},
	ReleaseSavepoint {
		txn_id: usize,
	},
	Scan {
		txn_id: usize,
		start: Bytes,
		end: Bytes,
		skip: Option<usize>,
		limit: Option<usize>,
		reverse: bool,
	},
	DirectPointRead {
		key: Bytes,
	},
	DirectScan {
		start: Bytes,
		end: Bytes,
		skip: Option<usize>,
		limit: Option<usize>,
		reverse: bool,
	},
	Commit {
		txn_id: usize,
	},
	Cancel {
		txn_id: usize,
	},
	MaintenanceCleanup,
	MaintenanceGc,
	CrashAndReload,
}

/// A transaction tracked in the generator to select valid actions.
#[derive(Debug, Clone, Copy)]
struct ActiveTxnMeta {
	id: usize,
	write: bool,
	savepoint_depth: usize,
}

/// Deterministic, PRNG seed-driven workload generator.
pub struct WorkloadGenerator {
	rng: StdRng,
	key_pool_size: usize,
	next_txn_id: usize,
	active_txns: Vec<ActiveTxnMeta>,
	enable_persistence_faults: bool,
	max_concurrent_txns: usize,
}

impl WorkloadGenerator {
	/// Creates a new generator with the given seed and key pool size.
	pub fn new(seed: u64, key_pool_size: usize) -> Self {
		Self {
			rng: StdRng::seed_from_u64(seed),
			key_pool_size,
			next_txn_id: 0,
			active_txns: Vec::new(),
			enable_persistence_faults: false,
			max_concurrent_txns: 8,
		}
	}

	/// Enables or disables crash and reload actions (for persistent storage tests).
	pub const fn with_persistence_faults(mut self, enabled: bool) -> Self {
		self.enable_persistence_faults = enabled;
		self
	}

	/// Sets the maximum concurrent transactions.
	pub const fn with_max_concurrent_txns(mut self, max: usize) -> Self {
		self.max_concurrent_txns = max;
		self
	}

	fn random_key(&mut self) -> Bytes {
		let id = self.rng.random_range(0..self.key_pool_size);
		Bytes::from(format!("k_{id:04}"))
	}

	fn random_value(&mut self) -> Bytes {
		let id = self.rng.random_range(0..1000);
		Bytes::from(format!("v_{id:06}"))
	}

	fn random_range(&mut self) -> (Bytes, Bytes) {
		let k1 = self.random_key();
		let k2 = self.random_key();
		if k1 <= k2 {
			(k1, k2)
		} else {
			(k2, k1)
		}
	}

	/// Produces the next deterministic action.
	pub fn next_action(&mut self) -> SimAction {
		// If no active transactions exist, begin a new one
		if self.active_txns.is_empty() {
			return self.gen_begin();
		}

		let choice = self.rng.random_range(0..100);

		// 15% chance to begin a new concurrent transaction if room allows
		if choice < 15 && self.active_txns.len() < self.max_concurrent_txns {
			return self.gen_begin();
		}

		// 5% chance of maintenance operations (cleanup / gc)
		if choice < 18 {
			return SimAction::MaintenanceCleanup;
		}
		if choice < 20 {
			return SimAction::MaintenanceGc;
		}

		// 5% chance of direct unattached reads / scans
		if choice < 23 {
			let key = self.random_key();
			return SimAction::DirectPointRead {
				key,
			};
		}
		if choice < 25 {
			let (start, end) = self.random_range();
			let reverse = self.rng.random_bool(0.3);
			let skip = if self.rng.random_bool(0.3) {
				Some(self.rng.random_range(0..5))
			} else {
				None
			};
			let limit = if self.rng.random_bool(0.5) {
				Some(self.rng.random_range(1..10))
			} else {
				None
			};
			return SimAction::DirectScan {
				start,
				end,
				skip,
				limit,
				reverse,
			};
		}

		// 1% chance of crash and reload if enabled
		if self.enable_persistence_faults && choice == 99 {
			self.active_txns.clear();
			return SimAction::CrashAndReload;
		}

		// Otherwise pick an active transaction to advance
		let txn_idx = self.rng.random_range(0..self.active_txns.len());
		let txn = self.active_txns[txn_idx];

		if txn.write {
			self.gen_write_txn_action(txn_idx)
		} else {
			self.gen_read_txn_action(txn_idx)
		}
	}

	fn gen_begin(&mut self) -> SimAction {
		let id = self.next_txn_id;
		self.next_txn_id += 1;
		let write = self.rng.random_bool(0.7);
		let mode = if self.rng.random_bool(0.6) {
			ModelIsolation::SerializableSnapshotIsolation
		} else {
			ModelIsolation::SnapshotIsolation
		};

		self.active_txns.push(ActiveTxnMeta {
			id,
			write,
			savepoint_depth: 0,
		});

		SimAction::Begin {
			txn_id: id,
			write,
			mode,
		}
	}

	fn gen_read_txn_action(&mut self, txn_idx: usize) -> SimAction {
		let txn = self.active_txns[txn_idx];
		let choice = self.rng.random_range(0..100);

		if choice < 45 {
			SimAction::Get {
				txn_id: txn.id,
				key: self.random_key(),
			}
		} else if choice < 65 {
			SimAction::Exists {
				txn_id: txn.id,
				key: self.random_key(),
			}
		} else if choice < 80 {
			let (start, end) = self.random_range();
			let reverse = self.rng.random_bool(0.3);
			let skip = if self.rng.random_bool(0.3) {
				Some(self.rng.random_range(0..5))
			} else {
				None
			};
			let limit = if self.rng.random_bool(0.5) {
				Some(self.rng.random_range(1..10))
			} else {
				None
			};
			SimAction::Scan {
				txn_id: txn.id,
				start,
				end,
				skip,
				limit,
				reverse,
			}
		} else if choice < 95 {
			self.active_txns.remove(txn_idx);
			SimAction::Commit {
				txn_id: txn.id,
			}
		} else {
			self.active_txns.remove(txn_idx);
			SimAction::Cancel {
				txn_id: txn.id,
			}
		}
	}

	fn gen_write_txn_action(&mut self, txn_idx: usize) -> SimAction {
		let txn = &mut self.active_txns[txn_idx];
		let txn_id = txn.id;
		let choice = self.rng.random_range(0..100);

		if choice < 25 {
			// Set
			SimAction::Set {
				txn_id,
				key: self.random_key(),
				val: self.random_value(),
			}
		} else if choice < 35 {
			// Get
			SimAction::Get {
				txn_id,
				key: self.random_key(),
			}
		} else if choice < 45 {
			// GetForUpdate
			SimAction::GetForUpdate {
				txn_id,
				key: self.random_key(),
			}
		} else if choice < 55 {
			// Del
			SimAction::Del {
				txn_id,
				key: self.random_key(),
			}
		} else if choice < 65 {
			// Put
			SimAction::Put {
				txn_id,
				key: self.random_key(),
				val: self.random_value(),
			}
		} else if choice < 72 {
			// PutC
			let chk = if self.rng.random_bool(0.5) {
				Some(self.random_value())
			} else {
				None
			};
			SimAction::PutC {
				txn_id,
				key: self.random_key(),
				val: self.random_value(),
				chk,
			}
		} else if choice < 78 {
			// DelC
			let chk = if self.rng.random_bool(0.5) {
				Some(self.random_value())
			} else {
				None
			};
			SimAction::DelC {
				txn_id,
				key: self.random_key(),
				chk,
			}
		} else if choice < 82 {
			// Savepoint
			txn.savepoint_depth += 1;
			SimAction::SetSavepoint {
				txn_id,
			}
		} else if choice < 85 && txn.savepoint_depth > 0 {
			// Rollback savepoint
			txn.savepoint_depth -= 1;
			SimAction::RollbackSavepoint {
				txn_id,
			}
		} else if choice < 87 && txn.savepoint_depth > 0 {
			// Release savepoint
			txn.savepoint_depth -= 1;
			SimAction::ReleaseSavepoint {
				txn_id,
			}
		} else if choice < 92 {
			// Scan
			let (start, end) = self.random_range();
			let reverse = self.rng.random_bool(0.3);
			let skip = if self.rng.random_bool(0.3) {
				Some(self.rng.random_range(0..5))
			} else {
				None
			};
			let limit = if self.rng.random_bool(0.5) {
				Some(self.rng.random_range(1..10))
			} else {
				None
			};
			SimAction::Scan {
				txn_id,
				start,
				end,
				skip,
				limit,
				reverse,
			}
		} else if choice < 97 {
			// Commit
			self.active_txns.remove(txn_idx);
			SimAction::Commit {
				txn_id,
			}
		} else {
			// Cancel
			self.active_txns.remove(txn_idx);
			SimAction::Cancel {
				txn_id,
			}
		}
	}
}
